### ISSUE TITLE
Hi, I can't access to google drive dataset

### ISSUE THREAD

**Issue by joannekim0420** [showlab/Q2A#1]
Hi, I was trying download the training dataset for Q2A and had some problem.
The google drive redirect page on your readme page outputs 404 error message. (I've tried several times and on chrome, microsoft edge) 
problem sovled

**Comment by chenjoya** [comment]
Hi, thanks for your question! 

You can fill in this table https://forms.gle/VshexUU5fCgmsHQ26 and then we will send you the link. 

Sorry for the confusion and we have updated the readme.md ;)
