### ISSUE TITLE
The videoreader may cause memory shortage when decoding long videos

### ISSUE THREAD

**Issue by tomchen-ctj** [showlab/Q2A#3]
Hi, Joya!

Thank you for your solid work and code releases!

I encountered a memory shortage issue while extracting visual features on a 64GB server. If possible, could you please share the visual embedding used in your experiments? (video.pth)

Thanks!

**Comment by tomchen-ctj** [comment]
By modifying the `torchvision.io.read_video` to `Decord.VideoReader` in `encoder/data.py`, I was able to resolve the memory issue. I recommend others who have limited RAM and encounter the same problem to try this approach. :)

Thank you once again for your code and solid work. Now I'm closing the issue.

**Comment by chenjoya** [comment]
Sorry for the late response. Great solutions and a huge thanks!

You can also use VideoReader API (https://pytorch.org/vision/main/generated/torchvision.io.VideoReader.html). It is very fast and supports frame-by-frame video loading. I also use it in my current projects.

Best,
Joya
